update by jll.Git.sh @ 2017-06-21 14:57:54 Solve the compiled issue about undefined reference to 'pow', 'clock_nanosleep' and so on. Remove the old patch for solving the above same compiled issue. Add the automatical building production tools 'jll.maker.sh' to support for perl building